### ISSUE TITLE
Image can only be viewed from "Evaluate Expression" or explicit variable watch

### ISSUE THREAD

**Issue by alexx-km** [srwi/PyCharm-PixelLens#18]
When I want to view an image which is a member variable of a class, I need to manually add a watch or directly access the variable via Evaluate Expression to be able to view the image.

Working:
![image](https://github.com/user-attachments/assets/c9e901ef-61bb-49c9-b55f-38a2143d019e)
![image](https://github.com/user-attachments/assets/33820c96-fade-416f-81ea-a9ba59aa546f)

Not working:
![image](https://github.com/user-attachments/assets/d4ef3b9e-d0e0-4129-975f-920eb083b0ab)

PyCharm Version: 2024.2.0.1

**Comment by srwi** [comment]
Good catch! I'll try to find some time to look into it soon.

**Comment by srwi** [comment]
Hi @alexx-km, the bug was fixed in the 0.2.4 release. You can either download it manually from the releases section or wait for it to be approved by JetBrains (probably 1-2 days).
