### ISSUE TITLE
Zoom should be focused on the mouse pointer

### ISSUE THREAD

**Issue by kirillkh** [srwi/PyCharm-PixelLens#39]
When zooming in with Ctrl+mouse wheel, what I want to see is more detail at a specific part of the image. The most natural way to achieve that is to place the mouse pointer over the area of interest before zooming in. The viewer is then supposed to keep the pixel coordinates under the mouse pointer fixed while zooming in the rest of the image. Most image viewers do that.

Zoom-out should ideally do the same. It's less important for zoom-out, but also helps track the context of the image.

After zooming in, I'm forced to use the scrollbars to locate the area of interest again and again. It's a major hurdle for me.

**Comment by srwi** [comment]
I added zooming in onto the cursor position. I'll try to get out a release rather soon.

**Comment by kirillkh** [comment]
Awesome work! Thanks a lot!
